Confirm URL fix for multistore.
getkevin/kevin-opencart-3.0.x pull request #5
Opened 2021-12-10 13:15 UTC by Agnet-group

2021-12-10 14:34 UTC, saltanovas requested changes

2021-12-10 14:34 UTC, saltanovas commented on upload/catalog/controller/extension/payment/kevin.php
> +		//	$confirm_url = HTTPS_SERVER . 'index.php?route=extension/payment/kevin/confirm';
Don't leave comments. Just delete them. Do changes in all repos

2021-12-13 14:00 UTC, tomas-maciulis approved these changes
Can be merged after requested changes are fulfilled.

2021-12-13 14:21 UTC, saltanovas commented
@tomas-maciulis changes was applied to another pr somehow :) 

@Agnet-group galėtum gal nuo šiol visus vienos repositorijos pakeitimus daryti viename pr? nes dabar visi šito repo pakeitimai padaryti į dar du naujus ir atksirus pr :)

2021-12-13 14:21 UTC, closed without merging